# Generated by Django 5.2.8 on 2025-11-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=50)),
                ('total_amount', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=255)),
            ],
        ),
    ]
