# Generated by Django 5.2.8 on 2025-11-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extracteddata',
            old_name='customer_name',
            new_name='industry',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='customer_concentration',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='ebitda',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='market_size',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='revenue',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
