# Generated by Django 5.2.8 on 2025-11-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_rename_customer_name_extracteddata_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteddata',
            name='customer_concentration',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='ebitda',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='market_size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='revenue',
            field=models.FloatField(null=True),
        ),
    ]
