# Generated by Django 5.2.8 on 2025-11-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_alter_extracteddata_customer_concentration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddata',
            name='file_hash',
            field=models.CharField(default='xxxxxxxxxx', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
