# Generated by Django 5.2.8 on 2025-11-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_extracteddata_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddata',
            name='company_name',
            field=models.CharField(default='xxxxx', max_length=255),
            preserve_default=False,
        ),
    ]
