# Generated by Django 5.2.8 on 2025-11-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_extracteddata_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteddata',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='file_hash',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='industry',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
